'use client';

import { motion, Variants } from 'framer-motion';
import { ShieldCheck, Users, Zap, Hexagon, Component, Flame } from 'lucide-react';

export default function AboutPage() {
  const containerVariants: Variants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
  };

  const itemVariants: Variants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { type: 'spring', stiffness: 100 } }
  };

  return (
    <motion.div 
      className="max-w-4xl mx-auto py-12 px-4 sm:px-6 z-10 relative"
      variants={containerVariants}
      initial="hidden"
      animate="visible"
    >
      <div className="text-center mb-16">
        <motion.div variants={itemVariants} className="inline-flex items-center justify-center w-20 h-20 bg-lucky-orange/20 rounded-2xl border-2 border-lucky-orange/50 mb-6 shadow-[0_0_30px_rgba(247,147,26,0.2)]">
          <Hexagon className="w-10 h-10 text-lucky-orange" />
        </motion.div>
        <motion.h1 variants={itemVariants} className="text-5xl md:text-6xl font-display font-bold text-white mb-6">
          Our Manifesto: <br/>
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-lucky-orange to-yellow-400">
            The Power of the Swarm
          </span>
        </motion.h1>
        <motion.p variants={itemVariants} className="text-xl md:text-2xl text-gray-400 max-w-2xl mx-auto leading-relaxed">
          We believe Bitcoin was meant to be productive. LuckyHive is built on a simple conviction: saving should be a shared victory, not a lonely grind for pennies.
        </motion.p>
      </div>

      <div className="space-y-12 mb-16">
        <motion.div variants={itemVariants} className="glass-panel p-8 md:p-12 relative overflow-hidden group">
          <div className="absolute top-0 right-0 w-64 h-64 bg-red-500/5 rounded-full blur-3xl -mt-20 -mr-20"></div>
          <div className="absolute bottom-0 left-0 w-64 h-64 bg-lucky-orange/5 rounded-full blur-3xl -mb-20 -ml-20"></div>
          <h2 className="text-3xl font-display font-bold text-white mb-8 text-center sm:text-left">The Old World vs. The Hive</h2>
          <div className="grid md:grid-cols-2 gap-8 relative z-10">
            <div className="bg-lucky-dark/40 p-6 rounded-xl border border-red-500/20">
              <h3 className="text-lg font-semibold text-red-400 flex items-center gap-2 mb-3">
                <Flame className="w-5 h-5" /> Traditional Finance
              </h3>
              <p className="text-gray-400 leading-relaxed text-sm">
                Institution-grade savings are a lonely, extractive experience. You save in a vacuum, earning a fraction of a percent, while the bank keeps the lion&apos;s share of the yield generated by your money. A &quot;shot at winning&quot; usually means risking what you already have.
              </p>
            </div>
            <div className="bg-lucky-dark/40 p-6 rounded-xl border border-lucky-orange/30">
              <h3 className="text-lg font-semibold text-lucky-orange flex items-center gap-2 mb-3">
                <Zap className="w-5 h-5" /> LuckyHive Protocol
              </h3>
              <p className="text-gray-300 leading-relaxed text-sm">
                We reject that trade-off. We believe protecting your principal is a fundamental right. By pooling the collective energy of our Bitcoin, we transform tiny, fragmented interest into life-changing opportunities for one another. 
              </p>
            </div>
          </div>
        </motion.div>

        <motion.h2 variants={itemVariants} className="text-3xl font-display font-bold text-center text-white mb-8">
          The Way of the Hive
        </motion.h2>

        <div className="grid md:grid-cols-3 gap-6">
          <motion.div variants={itemVariants} className="glass-panel p-6 flex flex-col items-start border-t-4 border-t-lucky-accent hover:-translate-y-2 transition-transform duration-300 cursor-default">
            <Component className="w-10 h-10 text-lucky-accent mb-4" />
            <h3 className="text-xl font-bold text-white mb-3">Productive, Not Passive</h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              For too long, the narrative has been that Bitcoin is meant to sit still in cold storage. We believe Bitcoin is at its best when it&apos;s active and industrious. Your principal is your fortress; the yield is our shared prize.
            </p>
          </motion.div>

          <motion.div variants={itemVariants} className="glass-panel p-6 flex flex-col items-start border-t-4 border-t-lucky-orange hover:-translate-y-2 transition-transform duration-300 cursor-default">
            <Users className="w-10 h-10 text-lucky-orange mb-4" />
            <h3 className="text-xl font-bold text-white mb-3">Community-Shared Fate</h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              We are moving away from individual gambling toward collective luck. We are building a digital well for the everyday holders. When one bee wins, the entire Hive celebrates the victory.
            </p>
          </motion.div>

          <motion.div variants={itemVariants} className="glass-panel p-6 flex flex-col items-start border-t-4 border-t-blue-400 hover:-translate-y-2 transition-transform duration-300 cursor-default">
            <ShieldCheck className="w-10 h-10 text-blue-400 mb-4" />
            <h3 className="text-xl font-bold text-white mb-3">Hardcoded Integrity</h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              We don&apos;t ask for your trust; we build with conviction. Our rules are written in immutable code that cannot be bargained with. The Hive Mind is always fair, transparent, and neutral. Your principal never leaves the Hive.
            </p>
          </motion.div>
        </div>
      </div>

      <motion.div variants={itemVariants} className="text-center py-12 px-6 glass-panel border border-lucky-orange/30 bg-lucky-orange/5 rounded-2xl relative overflow-hidden">
        <div className="absolute inset-0 honeycomb-pattern opacity-30"></div>
        <div className="relative z-10">
          <h2 className="text-3xl font-display font-bold text-white mb-4">Our Promise to the Swarm</h2>
          <p className="text-lg text-gray-300 mb-8 max-w-2xl mx-auto">
            We aren&apos;t here to sell you a financial product. We are here to build a better way to save, together. Welcome to the Hive.
          </p>
          <a href="/hive" className="inline-block glass-button px-8 py-4 text-lg font-bold">
            Let&apos;s make some honey
          </a>
        </div>
      </motion.div>
    </motion.div>
  );
}
